title                 : JAL Space
url                   : http://georgy-july.github.io
baseurl               : ""
email                 : juliyl64@gmail.com
description: >- 
 Cool music bits creation and music arrangements, live guitar music. 
 Создание музыкальных отрывков, аранжировка музыки, запись живой гитары.
github_username       : georgy-july
minimal_mistakes_skin : default
search                : true

markdown              : kramdown
remote_theme          : mmistakes/minimal-mistakes
permalink             : /:title/
paginate              : 5
paginate_path         : /page:num/
timezone              : Europe/Moscow
date_format           : "%Y-%m-%d"
locale                : "ru-RU"

teaser                : /assets/images/default/teaserfallback.png
logo                  : /assets/images/default/logo.png

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name                : "Juliy Leonov"
  avatar              : "/assets/images/default/bio-photo.jpg"
  bio                 : "Это я!"
  location            : "Москва, Россия"
  links:
    - label           : "GitHub"
      icon            : "fab fa-fw fa-github"
      url             : "https://github.com/"
    - label           : "LinkedIn"
      icon            : "fab fa-fw fa-linkedin"
      url             : "https://www.linkedin.com/"
    - label           : "SoundCloud"
      icon            : "fab fa-fw fa-soundcloud"
      url             : "https://soundcloud.com/juliy_l/"

footer:
  links:
    - label           : "GH"
      icon            : "fab fa-fw fa-github"
      url             : "https://github.com/"
    - label           : "LI"
      icon            : "fab fa-fw fa-linkedin"
      url             : "https://www.linkedin.com/"
    - label           : "SC"
      icon            : "fab fa-fw fa-soundcloud"
      url             : "https://soundcloud.com/juliy_l/"
encoding              : "utf-8"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: false
      comments: false
      share: false
      related: false
      show_date: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
